preset: psr2

enabled:
  - alpha_ordered_imports
  - binary_operator_spaces
  - blank_line_before_return
  - concat_with_spaces
  - declare_strict_types
  - function_typehint_space
  - hash_to_slash_comment
  - linebreak_after_opening_tag
  - lowercase_cast
  - method_separation
  - native_function_casing
  - new_with_braces
  - no_alias_functions
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_before_namespace
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_block_blank_lines
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_unneeded_control_parentheses
  - no_unreachable_default_argument_value
  - no_unused_imports
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - non_printable_character
  - normalize_index_brace
  - object_operator_without_whitespace
  - phpdoc_add_missing_param_annotation
  - phpdoc_indent
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_order
  - phpdoc_scalar
  - phpdoc_single_line_var_spacing
  - phpdoc_trim
  - phpdoc_types
  - self_accessor
  - phpdoc_var_without_name
  - return_type_declaration
  - short_array_syntax
  - short_scalar_cast
  - single_quote
  - standardize_not_equals
  - ternary_operator_spaces
  - trailing_comma_in_multiline_array
  - whitespace_after_comma_in_array

finder:
  name:
    - "*.php"
  exclude:
    - ".Build"
    - "Documentation"
    - "Libraries"
  not-name:
    - "ext_emconf.php"
    - "ext_localconf.php"
    - "ComposerPackagesCommands.php"
