preset: psr2

enabled:
    - no_leading_import_slash
    - no_trailing_comma_in_singleline_array
    - no_singleline_whitespace_before_semicolons
    - no_unused_imports
    - concat_with_spaces
    - no_whitespace_in_blank_line
    - ordered_imports
    - single_quote
    - no_extra_consecutive_blank_lines
    - phpdoc_no_package
    - phpdoc_scalar
    - no_blank_lines_after_phpdoc
    - short_array_syntax
    - whitespace_after_comma_in_array
    - function_typehint_space
    - hash_to_slash_comment
    - no_alias_functions
    - lowercase_cast
    - no_leading_namespace_whitespace
    - native_function_casing
    - no_empty_statement
    - self_accessor
    - no_short_bool_cast
    - no_unneeded_control_parentheses

finder:
  name:
    - "*.php"
  not-path:
    - ".Build"
    - "Documentation"
    - "Libraries"
