<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return [
    'Symfony\\Component\\Process\\' => [$vendorDir.'/symfony/process'],
    'Symfony\\Component\\Console\\' => [$vendorDir.'/symfony/console'],
];
