#!/usr/bin/env php
<?php
call_user_func(function () {
    if (getenv('TYPO3_PATH_WEB')) {
        $installationRootPath = rtrim(getenv('TYPO3_PATH_WEB'), '\\/');
    } else {
        $installationRootPath = __DIR__ . '/{$relative-web-dir}';
        putenv('TYPO3_PATH_WEB=' . $installationRootPath);
    }

    /**
     * Bootstrap for the command line
     */
    if (isset($installationRootPath)) {
        require $installationRootPath . '/typo3conf/ext/typo3_console/Scripts/typo3cms.php';
    } else {
        echo "Could not find typo3cms.php, make sure your path is within a TYPO3 installation and/or EXT:typo3_console is installed.\n";
        exit(1);
    }
});
